apiVersion: v1
kind: Pod
metadata:
  name: redis-restore
spec:
  volumes:
    - name: redis-data
      persistentVolumeClaim:
        claimName: redis-data-redis-master-0
  containers:
    - name: restore
      image: docker.io/library/busybox:latest
      command:
        - /bin/sh
      args:
        - -c
        - sleep infinity
      volumeMounts:
        - name: redis-data
          mountPath: /data
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 1001
  restartPolicy: Always
  nodeName: $pv_node
  securityContext:
    fsGroup: 1001
