= Getting Started

This page describes how to order a new managed Redis instance and consume it in an application.

Target Audience::
Service Consumer (Developer)

== Prerequisites

* `kubectl`

== Steps

. Create a new namespace `my-project`.
+
[source,bash]
----
kubectl create namespace my-project
----

. Create the following new `RedisInstance` resource in a new `instance.yaml` file.
+
.instance.yaml
[source,yaml]
----
include::example$getting-started-instance.yaml[]
----
<1> Name of the instance.
    Be sure to not make it too long.

. Apply the resource.
+
[source,bash]
----
kubectl apply -f instance.yaml
----

. Wait until the instance is ready.
+
[source,bash]
----
kubectl -n my-project wait --for condition=Ready RedisInstance.syn.tools/my-instance --timeout 180s
----

. Verify that there's a new `Secret` generated in the `my-project` namespace.
+
[source,bash]
----
kubectl -n my-project get secret my-instance-credentials
----

. Configure the application to use the credentials provided.
  For the purpose of this guide we will just run a Redis ping but it should demonstrate how to configure the Redis parameters for an app.
+
.app.yaml
[source,yaml]
----
include::example$getting-started-job.yaml[]
----

. Verify that the application can talk to Redis.
+
[source,bash]
----
kubectl wait -n my-project --for condition=Complete job/service-connection-verify
----

== Further Reading

* xref:references/api-spec.adoc[API Specification]
