= {page-component-title}

[discrete]
== Introduction

> Redis is an open source (BSD licensed), in-memory data structure store, used as a database, cache, and message broker.
Redis provides data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs, geospatial indexes, and streams.
Redis has built-in replication, Lua scripting, LRU eviction, transactions, and different levels of on-disk persistence, and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster.

This Application Catalog service provisions a managed Redis instance.
Features:

. Redis (single-node)
. Backup
. Metrics
. Alerting

[discrete]
== Documentation

The documentation is inspired by the https://documentation.divio.com/[Divio's documentation structure]:

Tutorials:: _Learning-oriented_: Simple lessons to learn about this project.

How-to guides:: _Problem-oriented_: step-by-step guides to achieve a goal.

Technical reference:: _Information-oriented_: explaining the inner ongoings.

Explanation:: _Understanding-oriented_: puts this project in context.
