apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  annotations:
    service.syn.tools/description: Redis key value store
    service.syn.tools/metadata: |
      {
        "displayName": "Redis",
        "documentationUrl": "https://kb.vshn.ch/app-catalog/redis.html",
        "shareable": true,
        "version": "6.0.10"
      }
    service.syn.tools/tags: |
      ["redis"]
  labels:
    service.syn.tools/id: redis-k8s
    service.syn.tools/name: redis-k8s
    service.syn.tools/updatable: "true"
  name: xredisinstances.syn.tools
spec:
  connectionSecretKeys:
    - endpoint
    - port
    - password
  group: syn.tools
  names:
    kind: XRedisInstance
    plural: xredisinstances
  claimNames:
    kind: RedisInstance
    plural: redisinstances
  defaultCompositionRef:
    name: redis
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.parameters.resources.storageSize
          name: Storage
          type: string
      name: v1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - parameters
              properties:
                parameters:
                  type: object
                  required:
                    - resources
                    - updatePolicy
                  properties:
                    resources:
                      type: object
                      description: Resources describes the compute resource requirements
                        (cpu, memory, storage)
                      required:
                        - storageSize
                      properties:
                        storageSize:
                          # we may need to use integer so that a policy engine can compare sizes and enforce a minimum and maximum size,
                          # unless policy engine supports unit suffixes like "Gi".
                          type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        limits:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          description: 'Limits describes the maximum amount of compute resources
                            allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                          type: object
                        requests:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          description: 'Requests describes the minimum amount of compute
                            resources required. If Requests is omitted for a container,
                            it defaults to Limits if that is explicitly specified, otherwise
                            to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                          type: object
                    updatePolicy:
                      type: object
                      required:
                        - version
                      properties:
                        version:
                          type: string
                        window: # ??
                          type: string
                    alerts:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: false
