apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  labels:
    name: provider-helm
  name: provider-helm
spec:
  # https://github.com/crossplane-contrib/provider-helm
  package: crossplane/provider-helm:v0.9.0
