= Restore Instance from Backup

This guide provides instructions how to perform data restores from backups.

Target Audience::
Service Provider (Engineer)

In general, the restore is done using the following steps:

. Prepare access to Restic repository
. Mount the desired Restic snapshot locally
. Copy the contents to the instance
. Restart the instance

== Requirements

- Admin access to service instance deployment
- `kubectl`
- `base64`
- `restic`
- `jq`

== Preparation

. Set basic variables
+
[source,bash]
----
app_namespace="your-app-namespace"
instance_name="the name of RedisInstance resource in $app_namespace"
----

. Gather information
+
[source,bash]
----
redis_composition=$(kubectl -n $app_namespace get RedisInstance $instance_name -o jsonpath="{.spec.resourceRef.name}")
redis_namespace="sv-redis-$redis_composition"
minio_composition=$(kubectl get xredisinstance $redis_composition -o jsonpath="{.spec.resourceRefs[3].name}")
minio_namespace="sv-minio-$redis_composition"
minio_pod=$(kubectl -n $minio_namespace get pods -o jsonpath="{.items[].metadata.name}")
s3_accesskey=$(kubectl -n $redis_namespace get secret $minio_composition -o jsonpath="{.data.accessKey}" | base64 -d)
s3_secretkey=$(kubectl -n $redis_namespace get secret $minio_composition -o jsonpath="{.data.secretKey}" | base64 -d)
s3_bucketname=$(kubectl -n $redis_namespace get s3bucket $minio_composition -o jsonpath="{.status.bucketName}")
restic_encryptionkey=$(kubectl -n $redis_namespace get secret "$redis_composition-password" -o jsonpath="{.data.repoEncryptionSecret}" | base64 -d)
pv_node=$(kubectl -n $redis_namespace get pod redis-master-0 -o jsonpath="{.spec.nodeName}")
----

. Set Restic variables
+
[source,bash]
----
export RESTIC_REPOSITORY="s3:http://localhost:9000/$s3_bucketname"
export RESTIC_PASSWORD=$restic_encryptionkey
export AWS_ACCESS_KEY_ID=$s3_accesskey
export AWS_SECRET_ACCESS_KEY=$s3_secretkey
----

== Restore

. Do a port-forward of the Minio instance that runs on the cluster.
+
[source,bash]
----
kubectl -n $minio_namespace port-forward pod/$minio_pod 9000:9000 > minio_portforward.log 2>&1 &
minio_pfid=$!
----

. Display the available snapshots
+
[source,bash]
----
restic snapshots
snapshot_id="" <1>
----
<1> Select the snapshot ID from the output of `restic snapshots`
+
[TIP]
====
If you just need the latest snapshot, set variable to `latest`:
[source,bash]
----
snapshot_id=latest
----
====

. Copy data to service instance
+
[NOTE]
====
In this step we're going to

. Stop the main Redis pod
. Create a temporary pod with Redis volume
. Copy the data to temporary pod
. Stop the temporary pod
. Start the main Redis pod
====
+
[source,bash]
----
kubectl -n $redis_namespace scale statefulset redis-master --replicas=0
kubectl -n $redis_namespace create -f - <<EOF
include::example$restore-pod.yaml[]
EOF
kubectl -n $redis_namespace wait --for condition=Ready pod/redis-restore
restic dump $snapshot_id /sv-redis-$redis_composition-redis.tar.gz | kubectl -n $redis_namespace exec -i redis-restore -- /bin/sh -c 'rm -r /data/* && tar -xzf - -C /'
kubectl -n $redis_namespace delete pod redis-restore
kubectl -n $redis_namespace scale statefulset redis-master --replicas=1
----

== Cleanup

[source,bash]
----
kill $minio_pfid
rm -rf minio_portforward.log
unset RESTIC_REPOSITORY RESTIC_PASSWORD AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
----
