apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  annotations:
    service.syn.tools/description: S3 Bucket on a supported platform
  name: xs3buckets.syn.tools
spec:
  connectionSecretKeys:
    - endpoint
    - accessKey
    - secretKey
  group: syn.tools
  names:
    kind: XS3Bucket
    plural: xs3buckets
  claimNames:
    kind: S3Bucket
    plural: s3buckets
  defaultCompositionRef:
    name: s3bucket
  versions:
    - additionalPrinterColumns:
        # - jsonPath: .spec.parameters.resources.storageSize
        #   name: Storage
        #   type: string
      name: v1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                bucketName:
                  type: string
                endpoint:
                  type: string
