fullnameOverride: minio-server
mode: standalone
persistence:
  size: 1Gi
replicas: 1
resources:
  requests:
    memory: 128Mi
rootUser: minioadmin
rootPassword: minioadmin
ingress:
  enabled: true
  path: /
  hosts:
    - minio.127.0.0.1.nip.io
